In [1]:
import pandas as pd
import numpy as np

In [156]:
df = pd.read_excel('mlr03.xls')
df.head()

*** No CODEPAGE record, no encoding_override: will use 'ascii'


EXAM1  EXAM2  EXAM3  FINAL
0     73     80     75    152
1     93     88     93    185
2     89     91     90    180
3     96     98    100    196
4     73     66     70    142

In [176]:
X = df.iloc[:, [0, 1, 2]].values
y = df.iloc[:, 3].values

In [177]:
x0 = np.ones(X.shape[0])
x0

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1.])

In [178]:
x0.shape = (25, 1)

In [179]:
new_X = np.hstack((x0, X))
new_X[0]

array([ 1., 73., 80., 75.])

In [180]:
theta = np.zeros((1, X.shape[1] + 1))
theta

array([[0., 0., 0., 0.]])

## Loop starts here

In [561]:
theta

array([[0.00399435, 0.32230198, 0.32405736, 0.33205033]])

In [827]:
# theta.shape, new_X.shape
for i in range(100):
    hypothesis = np.dot(theta, new_X)
    updater = hypothesis - y
#     print(updater)
    learning_rate = 0.000000001
    updater = learning_rate * updater
    dtheta = np.dot(updater, new_X.T)
    theta = theta - dtheta
print(updater, end = '\n\n\n')
print(theta)

[[ 1.63437958e-09 -3.32379795e-10  1.94851208e-09  2.16379952e-09
  -1.16421139e-09  2.84647472e-09 -6.59188581e-10 -5.01796794e-09
  -2.40203003e-09 -4.11328378e-09  1.91437200e-09 -7.44693536e-11
   3.96994219e-09  4.24740646e-09  1.02554415e-09 -4.59933728e-09
   1.79944726e-09 -4.97451183e-09  2.19913035e-09  1.34054243e-09
  -3.04782499e-09 -1.74997572e-09 -9.15372691e-09  5.88142459e-09
  -6.19249750e-10]]


[[0.00824849 0.66491042 0.66839401 0.68821716]]


In [832]:
p[0]*1 + p[1]*93 + p[2]*88 + p[3]*93

184.66778566613806

In [824]:
updater

array([[ 1.62035074e-09, -3.49342072e-10,  1.93185611e-09,
         2.14559599e-09, -1.17712021e-09,  2.83684719e-09,
        -6.72881295e-10, -5.02820920e-09, -2.41798397e-09,
        -4.12821131e-09,  1.90121536e-09, -8.75111073e-11,
         3.95279801e-09,  4.23323934e-09,  1.01176636e-09,
        -4.61660162e-09,  1.78600128e-09, -4.99096145e-09,
         2.18281153e-09,  1.32594029e-09, -3.06387363e-09,
        -1.76594457e-09, -9.16900124e-09,  5.86742869e-09,
        -6.36783202e-10]])

In [820]:
y

array([[152, 185, 180, 196, 142, 101, 149, 115, 175, 164, 141, 141, 184,
        152, 148, 192, 147, 183, 177, 159, 177, 175, 175, 149, 192]])

In [825]:
hypothesis

array([[153.62035074, 184.65065793, 181.93185611, 198.14559599,
        140.82287979, 103.83684719, 148.32711871, 109.9717908 ,
        172.58201603, 159.87178869, 142.90121536, 140.91248889,
        187.95279801, 156.23323934, 149.01176636, 187.38339838,
        148.78600128, 178.00903855, 179.18281153, 160.32594029,
        173.93612637, 173.23405543, 165.83099876, 154.86742869,
        191.3632168 ]])

In [826]:
hypothesis -y

array([[ 1.62035074, -0.34934207,  1.93185611,  2.14559599, -1.17712021,
         2.83684719, -0.67288129, -5.0282092 , -2.41798397, -4.12821131,
         1.90121536, -0.08751111,  3.95279801,  4.23323934,  1.01176636,
        -4.61660162,  1.78600128, -4.99096145,  2.18281153,  1.32594029,
        -3.06387363, -1.76594457, -9.16900124,  5.86742869, -0.6367832 ]])

In [549]:
# new_X = new_X.T

In [550]:
#theta.shape, new_X.shape

((1, 4), (4, 25))

In [551]:
hypothesis = np.dot(theta, new_X)
hypothesis

array([[74.32140325, 89.32893234, 88.01643441, 95.85733847, 68.12759851,
        50.22904849, 71.75329894, 53.19450561, 83.48551918, 77.3297162 ,
        69.13024472, 68.16481661, 90.93239218, 75.59044886, 72.08342059,
        90.64844812, 71.98949811, 86.11111152, 86.69068441, 77.56748267,
        84.14206639, 83.80317241, 80.22249159, 74.93196003, 92.57852069]])

In [552]:
hypothesis.shape, y.shape

((1, 25), (1, 25))

In [553]:
y = y.reshape(1, 25)

In [554]:
hypothesis.shape, y.shape

((1, 25), (1, 25))

In [555]:
updater = hypothesis - y
updater

array([[ -77.67859675,  -95.67106766,  -91.98356559, -100.14266153,
         -73.87240149,  -50.77095151,  -77.24670106,  -61.80549439,
         -91.51448082,  -86.6702838 ,  -71.86975528,  -72.83518339,
         -93.06760782,  -76.40955114,  -75.91657941, -101.35155188,
         -75.01050189,  -96.88888848,  -90.30931559,  -81.43251733,
         -92.85793361,  -91.19682759,  -94.77750841,  -74.06803997,
         -99.42147931]])

In [556]:
learning_rate = 0.000000001
updater = learning_rate * updater

In [557]:
dtheta = np.dot(updater, new_X.T)
dtheta

array([[-2.09476945e-06, -1.69005623e-04, -1.69921796e-04,
        -1.74215740e-04]])

In [558]:
theta.shape, dtheta.shape

((1, 4), (1, 4))

In [559]:
theta = theta - dtheta

In [560]:
theta

array([[0.00399435, 0.32230198, 0.32405736, 0.33205033]])

In [546]:
[-4.336102401240339, 0.35593822, 0.54251876, 1.16744422]

[-4.336102401240339, 0.35593822, 0.54251876, 1.16744422]

In [829]:
p = theta[0]

In [830]:
p

array([0.00824849, 0.66491042, 0.66839401, 0.68821716])

In [831]:
p[0]*1 + p[1]*73 + p[2]*80 + p[3]*75

153.6345164067426

In [49]:
# X = df.iloc[:, [0, 1, 2]].values
# y = df.iloc[:, 3].values

# # STEP 1
# np.random.seed(42)
# w = np.random.randn(1, X.shape[1])
# b = 0
# X = X.T
# for i in range(1, 3):
#     print('------------------------------------------------------------------------------------------')
#     print(i, end = '\n\n')
    
#     # STEP 2
#     z = np.dot(w, X) + b

#     # STEP 3
#     J = np.sum((z-y)**2) / (2 * X.shape[0])

#     # STEP 4
#     dz = (z - y) / (2 * X.shape[0])
#     dw = np.dot(dz, X.T)
#     print('dw = ', dw)
#     db = dz.sum()
#     print('db = ', db)

#     # STEP 5
#     w = w - 0.0001 * dw
#     b = b - 0.0001 * db
#     print(w, b)
#     print('------------------------------------------------------------------------------------------')
    